version: "3"
services:
  node:
    build: .
    image: iam-api:latest
    hostname: iam-api
    user: "node"
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
      - PORT=3001
    command: "npm start"
    ports:
     - "6997:3001"
    restart: always

